name: Chore
description: When you have a chore that needs to be done
labels: [chore]

body:
  - type: textarea
    id: chore
    attributes:
      label: "Describe the chore"
      description: "E.g. Rename the variable to id"
    validations:
      required: true
